version: '3'
services:
  mysql:
    container_name: ps-db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:8.0.2
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: ps-db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
      ADMIN_MAIL: admin@gmail.com 
      ADMIN_PASSWD: password
    networks:
      - prestashop_network
    volumes:
      - ./modules/samplemodule:/var/www/html/modules/samplemodule
      - ./controllers:/var/www/html/controllers
      - psdata:/var/www/html
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - prestashop_network

networks:
  prestashop_network:
volumes:
  psdata:
  dbdata:
